Website/Controllers/SubcontractorController.cs
using BuildOnTime.BusinessLogic;
using BuildOnTime.BusinessObject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    [BotAuthorize(Roles = "Administrator,Superintendent")]
    public class SubcontractorController : Controller
    {
        public static List<SubcontractorModel> subcontractorList = new List<SubcontractorModel>();

        // GET: Subcontractor
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(SubcontractorModel SubcontractorModel)
        {
            if (ModelState.IsValid)
            {
                int newId = subcontractorList.Count == 0 ? 0 : (subcontractorList.Max(sl => sl.Id) + 1);
                SubcontractorModel.Id = newId;
                subcontractorList.Add(SubcontractorModel);
                SubcontractorBLL.Create(new Subcontractor
                {
                    AddressLine1 = SubcontractorModel.AddressLine1,
                    AddressLine2 = SubcontractorModel.AddressLine2,
                    City = SubcontractorModel.City,
                    BuilderID = 3,
                    Name = SubcontractorModel.Name,
                    CellPhone = SubcontractorModel.CellPhone,
                    OfficeFax = SubcontractorModel.OfficeFax,
                    OfficePhone = SubcontractorModel.OfficePhone,
                    PostalCode = SubcontractorModel.PostalCode,
                    State = SubcontractorModel.State,

                });
                return RedirectToAction("List");

            }
            return View(SubcontractorModel);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Subcontractor sub = SubcontractorBLL.Read(id);
            return View(new SubcontractorModel
            {
                AddressLine1 = sub.AddressLine1,
                AddressLine2 = sub.AddressLine2,
                City = sub.City,
                CellPhone = sub.CellPhone,
                Id = (int) sub.Identifier,
                Email = sub.Email,
                Name = sub.Name,
                OfficeFax = sub.OfficeFax,
                OfficePhone = sub.OfficePhone,
                PostalCode = sub.PostalCode,
                State = sub.State,

            });
        }

        [HttpPost]
        public ActionResult Edit(SubcontractorModel SubcontractorModel)
        {
            if (ModelState.IsValid)
            {
                SubcontractorBLL.Update(new Subcontractor
                {
                    AddressLine1 = SubcontractorModel.AddressLine1,
                    AddressLine2 = SubcontractorModel.AddressLine2,
                    City = SubcontractorModel.City,
                    BuilderID = 3,
                    Name = SubcontractorModel.Name,
                    Identifier = SubcontractorModel.Id,
                    CellPhone = SubcontractorModel.CellPhone,
                    OfficeFax = SubcontractorModel.OfficeFax,
                    OfficePhone = SubcontractorModel.OfficePhone,
                    PostalCode = SubcontractorModel.PostalCode,
                    State = SubcontractorModel.State,

                });
                return RedirectToAction("List");
            }
            return View(SubcontractorModel);
        }

        [HttpGet]
        public ActionResult List()
        {
            List<Website.Models.SubcontractorListItemModel> subList = new List<SubcontractorListItemModel>();
            var storedSubList = SubcontractorBLL.List(3);
            foreach(var sub in storedSubList)
            {
                subList.Add(new SubcontractorListItemModel
                {
                    //CellPhone = sub.CellPhone,
                    CompanyName = sub.Name,
                    Id = (int)sub.Identifier,
                    Name = sub.Name,
                    OfficePhone = sub.OfficePhone,
                    OfficeFax = sub.OfficeFax,
                    CellPhone = sub.CellPhone,
                });
            }

            //List<Website.Models.SubcontractorListItemModel> subList = new List<SubcontractorListItemModel>();
            //foreach (SubcontractorModel sub in subcontractorList)
            //{
            //    subList.Add(new SubcontractorListItemModel
            //    {
            //        CellPhone = sub.CellPhone,
            //        CompanyName = sub.CompanyName,
            //        Id = sub.Id,
            //        Name = sub.Name,
            //        OfficePhone = sub.OfficePhone
            //    });
            //}
            return View(subList);
        }
    }
}

Website/Controllers/SuperController.cs
using BuildOnTime.BusinessLogic;
using BuildOnTime.BusinessObject;
using BuildOnTime.Presentation;
using Omu.ValueInjecter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Website.Models;

namespace Website.Controllers
{
    [BotAuthorize(Roles = "Administrator,Superintendent")]
    public class SuperController : Controller
    {
        public ActionResult Index()
        {
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            DailyTaskList dailyTasks = new DailyTaskList(employee);
            List<SelectListItem> itemList = new SelectList(WorkerPLL.List(employee.Builder), "Identifier", "Name").ToList();
            itemList.Insert(0, new SelectListItem { Text = "", Value = "" });
            ViewBag.WorkerList = new JavaScriptSerializer().Serialize(itemList.Select(sl => new { sl.Value, sl.Text }));
            return View("Index", dailyTasks);
        }

        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult Jobs()
        {
            HomeModel homeModel = new HomeModel();
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            DateTime cutOffDate = DateTime.Now.AddDays(-7);
            List<Job> jobList = JobBLL.Search(employee.Builder.Identifier, cutOffDate);
            List<Employee> employees = EmployeeBLL.List(employee.Builder);
            List<JobModel> jobModels = new List<JobModel>();
            foreach (Job job in jobList)
            {
                JobModel jobModel = new JobModel();
                jobModel.InjectFrom(job);
                jobModel.SuperName = employees.Find(delegate (Employee em) { return em.Identifier.Equals(job.SuperID); }).Name;
                homeModel.Jobs.Add(jobModel);
            }
            return View("Jobs", homeModel);
        }

        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult SubcontractorList()
        {
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            Builder builder = BuilderBLL.Read(employee.Builder.Identifier);
            List<Subcontractor> subcontractors = SubcontractorBLL.List(builder.Identifier);

            List<TaskModel> taskModels = new List<TaskModel>();
            return View("SubcontractorList", taskModels);
        }

        [HttpPost]
        public JsonResult AssignWorkerTask(TaskWorkerModel taskWorkerModel)
        {
            JobTask jobTask = JobTaskBLL.Read(taskWorkerModel.TaskID);
            JobTaskBLL.WorkerDissociate(jobTask);
            string employeeID = Worker.EmployeeID(taskWorkerModel.WorkerID);
            string subcontractorID = Worker.SubcontractorID(taskWorkerModel.WorkerID);
            if (employeeID != null)
            {
                JobTaskBLL.EmployeeAssociate(jobTask, employeeID);
            }
            else if (subcontractorID != null)
            {
                JobTaskBLL.SubcontractorAssociate(jobTask, subcontractorID);
            }
            return Json(new { Status = "Success" });
        }

        [HttpPost]
        public JsonResult AssignWorkersTasks(IEnumerable<TaskWorkerModel> tasksWorkers)
        {
            foreach (TaskWorkerModel taskWorkerModel in tasksWorkers)
            {
                JobTask jobTask = JobTaskBLL.Read(taskWorkerModel.TaskID);
                string employeeID = Worker.EmployeeID(taskWorkerModel.WorkerID);
                string subcontractorID = Worker.SubcontractorID(taskWorkerModel.WorkerID);
                if (employeeID != null)
                {
                    JobTaskBLL.EmployeeAssociate(jobTask, employeeID);
                }
                else if (subcontractorID != null)
                {
                    JobTaskBLL.SubcontractorAssociate(jobTask, subcontractorID);
                }
            }
            return Json(new { Status = "Success" });
        }


        [HttpPost]
        public JsonResult CalledWorkersTasks(List<TaskCommunicationModel> calledWorkers)
        {
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            Builder builder = BuilderBLL.Read(employee.Builder.Identifier);
            foreach (TaskCommunicationModel calledWorker in calledWorkers)
            {
                JobTask jobTask = JobTaskBLL.Read(calledWorker.TaskID);
                string employeeID = Worker.EmployeeID(calledWorker.WorkerID);
                string subcontractorID = Worker.SubcontractorID(calledWorker.WorkerID);

                //CommunicationReasonEnum communicationReason = (CommunicationReasonEnum)Enum.Parse(typeof(CommunicationReasonEnum), gridView.DataKeys[gridViewRow.RowIndex].Values["Reason"].ToString());
                if (subcontractorID != null)
                {
                    CommunicationPLL.SubcontractorCommunicate(employee.Builder.Identifier, subcontractorID, jobTask.Identifier, null, employee.Identifier, calledWorker.Reason, CommunicationMethodEnum.Phone, "blank");
                }
                if (employeeID != null)
                {
                    CommunicationPLL.EmployeeCommunicate(employee.Builder.Identifier, employeeID, jobTask.Identifier, null, employee.Identifier, calledWorker.Reason, CommunicationMethodEnum.Phone, "blank");
                }
            }
            return Json(new { Status = "Success" });
        }

        [HttpPost]
        public JsonResult ReviewedTasks(List<string> reviewedTasks)
        {
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            Builder builder = BuilderBLL.Read(employee.Builder.Identifier);
            foreach (string reviewedTask in reviewedTasks)
            {
                JobTask jobTask = JobTaskBLL.Read(reviewedTask);
                jobTask.Signoff = DateTime.Now;
                JobTaskBLL.Update(jobTask);
            }
            return Json(new { Status = "Success" });
        }

        [HttpPost]
        public JsonResult EmailTasks(List<TaskCommunicationModel> emailTasks)
        {
            List<CommunicationEMailTask> communicationTasks = new List<CommunicationEMailTask>();
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            Builder builder = BuilderBLL.Read(employee.Builder.Identifier);
            foreach (TaskCommunicationModel emailTask in emailTasks)
            {
                JobTask jobTask = JobTaskBLL.Read(emailTask.TaskID);
                string employeeID = Worker.EmployeeID(emailTask.WorkerID);
                string subcontractorID = Worker.SubcontractorID(emailTask.WorkerID);

                communicationTasks.Add(new CommunicationEMailTask(jobTask, employee, emailTask.Reason));
            }
            CommunicationPLL.SubcontractorEmail(communicationTasks);
            return Json(new { Status = "Success" });
        }

        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult SubcontractorView(int subcontractorid)
        {
            DateTime startDate = DateTime.Now.AddDays(-7);
            DateTime endDate = startDate.AddDays(365);
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            Builder builder = BuilderBLL.Read(employee.Builder.Identifier);
            Subcontractor subcontractor = SubcontractorBLL.Read(subcontractorid);
            List<SubJobTaskDisplay> jobTasks = SubcontractorPLL.SubcontractorTasks(builder, subcontractor, startDate, endDate);
            List<TaskModel> taskModels = new List<TaskModel>();
            foreach (SubJobTaskDisplay taskDisplay in jobTasks)
            {
                TaskModel taskModel = new TaskModel();
                taskModel.Builder = taskDisplay.BuilderName;
                taskModel.Duration = taskDisplay.TimeFrame;
                taskModel.Job = taskDisplay.JobName;
                taskModel.Name = taskDisplay.TaskName;
                taskModel.StartDate = taskDisplay.Start;
                taskModel.Status = taskDisplay.Status.ToString();
                taskModel.StatusDate = taskDisplay.Updated;
                taskModel.Super = taskDisplay.SuperName;
                taskModels.Add(taskModel);
            }
            return View("SubcontractorView", taskModels);
        }

        [HttpGet]
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult JobCalendar(int jobID)
        {
            Job job = JobBLL.Read(jobID);
            JobWorkerModel calendarModel = new JobWorkerModel();
            ViewBag.TitleDescription = job.Name;
            calendarModel.JobID = job.Identifier.ToString();
            calendarModel.JobName = job.Name;
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            calendarModel.Workers = WorkerPLL.List(employee.Builder);
            calendarModel.Jobs = JobBLL.ActiveJobs(employee.Builder.Identifier);
            return View("JobCalendar", calendarModel);
        }

        [HttpGet]
        [OutputCache(NoStore = true, Duration = 0)]
        public JsonResult JobCalendarEvents(int jobID)
        {
            Job job = JobBLL.Read(jobID);
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            List<JobEvent> events = CalendarEventPLL.JobEvents(employee, jobID);
            List<CalendarModel> calendarTasks = new List<CalendarModel>();
            foreach (JobEvent timeEvent in events)
            {
                CalendarModel model = new CalendarModel();
                model.allDay = true;
                // Take off one second so day is correct.  In database a job of one day to start Thursday May 24, 2012 would be stored start 05-24-2012 end 05-25-2012
                // this is how the web forms control handle it MVC FullCalendar wants them to be the same day.

Website/Views/Super/EMailsToSend.cshtml
@model IEnumerable<BuildOnTime.Presentation.TaskCommunicationAction>
<table id="TablePhoneEMailsToSend" class="dataTable table-striped">
    <thead>
        <tr>
            <th>
                E-Mail
            </th>
            <th>
                Job
            </th>
            <th>
                Task
            </th>
            <th>
                Worker
            </th>
            <th>
                Start
            </th>
            <th>
                Finish
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {    
            <tr>
                <td>
                    <input type="checkbox" class="CheckBoxEmail" name="@item.JobTaskID" />
                    <input type="hidden" class="WorkerID" name="@item.WorkerID" />
                    <input type="hidden" class="Reason" name="@item.Reason" />
                </td>
                <td>
                    @Html.ActionLink(item.JobName, "JobCalendar", "Super", new { jobID = item.JobID }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkerName)
                </td>
                <td>
                    @item.Start.ToString("MM/dd/yyyy")
                </td>
                <td>
                    @item.Finish.ToString("MM/dd/yyyy")
                </td>
            </tr>
        }
    </tbody>
</table>

Website/Views/Super/Index.cshtml
@model BuildOnTime.Presentation.DailyTaskList
@{
    ViewBag.Title = "Home";
}
@section Styles{
    <link href="@Url.Content("~/Content/DataTables/css/jquery.dataTables.css")" rel="stylesheet" type="text/css" />
}
@section Scripts{
    <script src="@Url.Content("~/Scripts/DataTables/jquery.dataTables.js")" type="text/javascript"></script>
    <script type="text/javascript">

        var selectValues = @Html.Raw(ViewBag.WorkerList);
        function postData(url, data, successFunction, errorFunction) {
            $.ajax({
                url: url,
                data: JSON.stringify(data),
                success: successFunction,
                error: errorFunction,
                type: 'POST',
                cache: false,
                contentType: 'application/json, charset=utf-8',
                dataType: 'json'
            });
        }

        function populateSelect() {
            $.each(selectValues, function (key, item) {
                $('.SelectWorker')
                .append($("<option></option>")
                .attr("value", item.Value)
                .text(item.Text));
            });
        }

        $(document).ready(function () {
            populateSelect();
            $('table').DataTable();
        });

        function refreshPage() {
            location.reload();
        }

        function assignWorkers() {
            var taskWorkerList = new Array();
            $('.SelectWorker option:selected').each(function () {
                if (($(this).val() != null) && ($(this).val().toString().length > 0)) {
                    taskWorkerList.push({ TaskID: $(this).parent().attr('name'), WorkerID: $(this).val() });
                }
            });
            if (taskWorkerList.length > 0) {
                postData('@Url.Content("~/Super/AssignWorkersTasks")', taskWorkerList, refreshPage);
            }
        }

        function sendEmails() {
            var emailList = new Array();
            $('input:checked[class=CheckBoxEmail]').each(function () {
                if (($(this).val() != null) && ($(this).val().toString().length > 0)) {
                    emailList.push({ TaskID: $(this).attr('name'), WorkerID: $(this).parent().children('.WorkerID').attr('name'), Reason: $(this).parent().children('.Reason').attr('name') });
                }
            });
            if (emailList.length > 0) {
                postData('@Url.Content("~/Super/EmailTasks")', emailList, refreshPage);
            }
        }

        function sendAllEmails() {
            var emailList = new Array();
            $('.CheckBoxEmail').each(function () {
                if (($(this).val() != null) && ($(this).val().toString().length > 0)) {
                    emailList.push({ TaskID: $(this).attr('name'), WorkerID: $(this).parent().children('.WorkerID').attr('name'), Reason: $(this).parent().children('.Reason').attr('name') });
                }
            });
            if (emailList.length > 0) {
                postData('@Url.Content("~/Super/EmailTasks")', emailList, refreshPage);
            }
        }

        function calledWorkers() {
            var calledList = new Array();
            $('input:checked[class=CheckBoxCall]').each(function () {
                if (($(this).val() != null) && ($(this).val().toString().length > 0)) {
                    calledList.push({ TaskID: $(this).attr('name'), WorkerID: $(this).parent().children('.WorkerID').attr('name'), Reason: $(this).parent().children('.Reason').attr('name') });
                }
            });
            if (calledList.length > 0) {
                postData('@Url.Content("~/Super/CalledWorkersTasks")', calledList, refreshPage);
            }
        }

        function reviewedTasks() {
            var reviewedList = new Array();
            $('input:checked[class=CheckBoxReviewed]').each(function () {
                if (($(this).val() != null) && ($(this).val().toString().length > 0)) {
                    reviewedList.push($(this).attr('name'));
                }
            });
            if (reviewedList.length > 0) {
                postData('@Url.Content("~/Super/ReviewedTasks")', reviewedList, refreshPage);
            }
        }
    </script>
}
<h2>
    Tasks in process and starting soon
</h2>
@{Html.RenderPartial("TasksInProcess", Model.InProcess);}
<h2>
    <label>
        Tasks to assign
    </label><input type="button" name="buttonAssign" value="Assign" onclick="assignWorkers();" />
</h2>
@{Html.RenderPartial("TaskAssign", Model.Assignments);}
<h2>
    Tasks not accepted
</h2>
@{Html.RenderPartial("TaskNotAccepted", Model.NotAccepted);}
<h2>
    <label>
        Phone calls to make
    </label><input type="button" name="buttonCalled" value="Called"
                   onclick="calledWorkers();" />
</h2>
@{Html.RenderPartial("PhoneCallsToMake", Model.PhoneCalls);}
<h2>
    <label>
        E-Mails to send
    </label><input type="button" name="buttonEMail" value="EMail" onclick="sendEmails();" /><input type="button" name="buttonEMailAll" value="EMail All" onclick="sendAllEmails();" />
</h2>
@{Html.RenderPartial("EMailsToSend", Model.EMails);}
<h2>
    <label>
        Tasks to review
    </label><input type="button" name="buttonReviewed" value="Reviewed"
                   onclick="reviewedTasks();" />
</h2>
@{Html.RenderPartial("TasksCompleted", Model.Reviews);}

Website/Views/Super/JobListPartial.cshtml
@model IEnumerable<Website.Models.JobModel>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table id="TableJobList" class="dataTable table-striped">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Super
            </th>
            <th>
                Description
            </th>
            <th>
                Permit
            </th>
            <th>
                Start
            </th>
            <th>
                Finish
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SuperName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Permit)
                </td>
                <td>
                    @(@item.start.HasValue ? @item.start.Value.ToString("MM/dd/yyyy") : "")
                </td>
                <td>
                    @(@item.finish.HasValue ? @item.finish.Value.ToString("MM/dd/yyyy") : "")
                </td>
                <td>
                    @Html.ActionLink("Calendar", "JobCalendar", new { jobID = item.Identifier })
                </td>
            </tr>
        }
    </tbody>
</table>

Website/Views/Super/Jobs.cshtml
@model Website.Models.HomeModel
@{
    ViewBag.Title = "Jobs";
}
@section Styles{
    <link href="@Url.Content("~/Content/DataTables/css/jquery.dataTables.css")" rel="stylesheet" type="text/css" />
}
@section Scripts{
    <script src="@Url.Content("~/Scripts/DataTables/jquery.dataTables.js")" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('table').DataTable();
        });
    </script>
}
<h2>Jobs</h2>

@{Html.RenderPartial("JobListPartial", Model.Jobs);}

Website/Views/Super/PhoneCallsToMake.cshtml
@model IEnumerable<BuildOnTime.Presentation.TaskCommunicationAction>
<table id="TablePhoneCallsToMake" class="dataTable table-striped">
    <thead>
        <tr>
            <th>
                Called
            </th>
            <th>
                Action
            </th>
            <th>
                Job
            </th>
            <th>
                Task
            </th>
            <th>
                Worker
            </th>
            <th>
                Contact
            </th>
            <th>
                Alternate
            </th>
            <th>
                Alternate
            </th>
            <th>
                Start
            </th>
            <th>
                Finish
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" class="CheckBoxCall" name="@item.JobTaskID" />
                    <input type="hidden" class="WorkerID" name="@item.WorkerID" />
                    <input type="hidden" class="Reason" name="@item.Reason" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reason)
                </td>
                <td>
                    @Html.ActionLink(item.JobName, "JobCalendar", "Super", new { jobID = item.JobID }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Channel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Channel2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Channel3)
                </td>
                <td>
                    @item.Start.ToString("MM/dd/yyyy")
                </td>
                <td>
                    @item.Finish.ToString("MM/dd/yyyy")
                </td>
            </tr>
        }
    </tbody>
</table>

Website/Views/Super/TaskAssign.cshtml
@model IEnumerable<BuildOnTime.Presentation.TaskAction>
<table id="TableTaskAssign" class="dataTable table-striped">
    <thead>
        <tr>
            <th>
                Job
            </th>
            <th>
                Task
            </th>
            <th>
                Worker
            </th>
            <th>
                Start
            </th>
            <th>
                Finish
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.JobName, "JobCalendar", "Super", new { jobID = item.JobID }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskName)
                </td>
                <td>
                    <select name="@item.JobTaskID" class="SelectWorker">
                    </select>
                </td>
                <td>
                    @item.Start.ToString("MM/dd/yyyy")
                </td>
                <td>
                    @item.Finish.ToString("MM/dd/yyyy")
                </td>
            </tr>
        }
    </tbody>
</table>

Website/Views/Super/TaskNotAccepted.cshtml
@model IEnumerable<BuildOnTime.Presentation.TaskAction>
<table id="TableTaskNotAccepted" class="dataTable table-striped">
    <thead>
        <tr>
            <th>
                Job
            </th>
            <th>
                Task
            </th>
            <th>
                Worker
            </th>
            <th>
                Start
            </th>
            <th>
                Finish
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.JobName, "JobCalendar", "Super", new { jobID = item.JobID }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkerName)
                </td>
                <td>
                    @item.Start.ToString("MM/dd/yyyy")
                </td>
                <td>
                    @item.Finish.ToString("MM/dd/yyyy")
                </td>
            </tr>
        }
    </tbody>
</table>

Website/Views/Super/TasksCompleted.cshtml
@model IEnumerable<BuildOnTime.Presentation.TaskAction>
<table id="TableTaskCompleted" class="dataTable table-striped">
    <thead>
        <tr>
            <th>
                Reviewed
            </th>
            <th>
                Job
            </th>
            <th>
                Task
            </th>
            <th>
                Worker
            </th>
            <th>
                Start
            </th>
            <th>
                Finish
            </th>
            <th>
                Finished
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" class="CheckBoxReviewed" name="@item.JobTaskID" />
                </td>
                <td>
                    @Html.ActionLink(item.JobName, "JobCalendar", "Super", new { jobID = item.JobID }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkerName)
                </td>
                <td>
                    @item.Start.ToString("MM/dd/yyyy")
                </td>
                <td>
                    @item.Finish.ToString("MM/dd/yyyy")
                </td>
                <td>
                    @((item.Finished.HasValue) ? item.Finished.Value.ToString("MM/dd/yyyy") : "")
                </td>
            </tr>
        }
    </tbody>
</table>

Website/Views/Super/TasksInProcess.cshtml
@model IEnumerable<BuildOnTime.Presentation.TaskAction>
<table id="TableInProcess" class="dataTable table-striped">
    <thead>
        <tr>
            <th>
                Job
            </th>
            <th>
                Task
            </th>
            <th>
                Worker
            </th>
            <th>
                Start
            </th>
            <th>
                Finish
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.JobName, "JobCalendar", "Super", new { jobID = item.JobID }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkerName)
                </td>
                <td>
                    @item.Start.ToString("MM/dd/yyyy")
                </td>
                <td>
                    @item.Finish.ToString("MM/dd/yyyy")
                </td>
            </tr>
        }
    </tbody>
</table>