Website/Controllers/JobController.cs
using BuildOnTime.BusinessLogic;
using BuildOnTime.BusinessObject;
using Omu.ValueInjecter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    [BotAuthorize(Roles = "Administrator,Superintendent")]
    public class JobController : Controller
    {
        //public static List<JobModel> jobList = new List<JobModel>(); 

        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult Index()
        {
            HomeModel homeModel = new HomeModel();
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            DateTime cutOffDate = DateTime.Now.AddDays(-7);
            List<Job> jobList = JobBLL.Search(employee.Builder.Identifier, cutOffDate);
            List<Employee> employees = EmployeeBLL.List(employee.Builder);
            List<JobModel> jobModels = new List<JobModel>();
            foreach (Job job in jobList)
            {
                JobModel jobModel = new JobModel();
                jobModel.InjectFrom(job);
                jobModel.SuperName = employees.Find(delegate (Employee em) { return em.Identifier.Equals(job.SuperID); }).Name;
                homeModel.Jobs.Add(jobModel);
            }
            return View(homeModel.Jobs);
        }

        //
        // GET: /Job/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Job/Create
        [HttpGet]
        public ActionResult Create()
        {
            JobModel jobModel = new JobModel();
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            List<Employee> supers = EmployeeBLL.ListSuper(employee.Builder);
            ViewBag.supers = supers;
            List<Schedule> schedules = ScheduleBLL.Search(employee.Builder.Identifier, null);
            ViewBag.schedules = schedules;
            return View(jobModel);
        }

        //
        // POST: /Job/Create

        [HttpPost]
        public ActionResult Create(JobModel model)
        {
            try
            {
                Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
                Job job = new Job();
                Job persistedJob = JobBLL.CreateJobSchedule((int)employee.Builder.Identifier, (int)model.SuperID, (int)model.ScheduleID.Value, model.start.Value, model.Name, model.Permit, model.Description, model.LotIdentifier, model.Address1, model.City, model.PostalCode, model.State);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Job/Edit/5

        public ActionResult Edit(int id)
        {
            Job job = JobBLL.Read(id);
            Site site = SiteBLL.Read(job.SiteID);
            JobModel jobModel = new JobModel();
            jobModel.InjectFrom(site);
            jobModel.InjectFrom(job);
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            List<Employee> supers = EmployeeBLL.ListSuper(employee.Builder);
            ViewBag.supers = supers;
            return View(jobModel);
        }

        //
        // POST: /Job/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, JobModel model)
        {
            try
            {
                Job job = JobBLL.Read(id);
                job.Identifier = id;
                Site site = SiteBLL.Read(job.SiteID);
                job.InjectFrom(model);
                site.InjectFrom(model);
                site.Identifier = job.SiteID;
                JobBLL.Update(job);
                SiteBLL.Update(site);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Job/Retire/5 
        public ActionResult Retire(int id)
        {
            Job job = JobBLL.Read(id);
            Employee employee = EmployeeBLL.ReadBySystemUser(Session["SystemUserID"]);
            JobBLL.Delete(job, (int)employee.Identifier, Request.UserHostAddress + ": " + Request.UserHostName + " - JobController.Delete");
            return RedirectToAction("Index");
        }

        //
        // POST: /Job/Delete/5
        [HttpPost]
        public ActionResult Retire(int id, FormCollection collection)
        {
            return Retire(id);
        }
    }
    // GET: Job
    //    public ActionResult Index()
    //    {
    //        return View();
    //    }

    //    [HttpGet]
    //    public ActionResult Create()
    //    {
    //        var asb = BuilderBLL.Read(3);
    //        var employeeList = EmployeeBLL.ListSuper(asb);
    //        var superList = new SelectList(employeeList.OrderBy(x => x.Name), "Identifier", "Name");
    //        ViewBag.SuperDropDownList = superList;
    //        return View();
    //    }

    //    [HttpPost]
    //    public ActionResult Create(JobModel JobModel)
    //    {
    //        if (ModelState.IsValid)
    //        {
    //            Site site = SiteBLL.Create(new Site
    //            {
    //                Address1 = JobModel.Address,
    //                BuilderID = 3,
    //                City = JobModel.City,
    //                LotIdentifier = JobModel.LotNumber,
    //                PostalCode = JobModel.PostalCode,
    //                State = JobModel.State
    //            });
    //            Job job = JobBLL.CreateJobSchedule(3, JobModel.SuperId,  6, JobModel.Start, JobModel.Name, JobModel.Permit, JobModel.Description, JobModel.LotNumber, JobModel.Address, JobModel.City, JobModel.PostalCode, JobModel.State);
    //            return RedirectToAction("List");

    //        }
    //        return View(JobModel);
    //    }

    //    [HttpGet]
    //    public ActionResult Edit(int id)
    //    {
    //        JobModel job = jobList.FirstOrDefault(sl => sl.Id == id);
    //        return View(job);
    //    }

    //    [HttpPost]
    //    public ActionResult Edit(JobModel JobModel)
    //    {
    //        if (ModelState.IsValid)
    //        {
    //            JobModel job = jobList.FirstOrDefault(sl => sl.Id == JobModel.Id);
    //            jobList.Remove(job);
    //            jobList.Add(JobModel);
    //            return RedirectToAction("List");
    //        }
    //        return View(JobModel);
    //    }

    //    [HttpGet]
    //    public ActionResult List()
    //    {
    //        List<Website.Models.JobListItemModel> jobList = new List<JobListItemModel>();
    //        var storedJobList = JobBLL.ActiveJobs(3);
    //        foreach(var job in storedJobList)
    //        {
    //            var site = SiteBLL.Read(job.SiteID);
    //            var super = EmployeeBLL.Read(job.SuperID);
    //            jobList.Add(new JobListItemModel
    //            {
    //                Description = job.Description,
    //                Finish = job.finish?.ToString(),                                          
    //                Id = job.Identifier.Value,
    //                LotNumber = site.LotIdentifier,
    //                Permit = job.Permit,
    //                Start = job.start?.ToString(),
    //                Superintendent = super.FirstName + " " + super.LastName,
    //            });
    //        }

    //        //List<Website.Models.JobListItemModel> jobList = new List<JobListItemModel>();
    //        //foreach (JobModel job in jobList)
    //        //{
    //        //    jobList.Add(new JobListItemModel
    //        //    {
    //        //      LotNumber = job.LotNumber,
    //        //        Id = (int)job.Identifier,
    //        //        Superintendent = job.Superintendent,
    //        //        Description = job.Description,
    //        //        Permit = job.Permit,
    //        //        Start = job.Start,
    //        //        Finish = job.Finish,
    //        //    });
    //        //}
    //        return View(jobList);
    //    }
    //}
}

Website/Views/Job/Create.cshtml
@model Website.Models.JobModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Job</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>JobModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.LotIdentifier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LotIdentifier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LotIdentifier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SuperName, htmlAttributes: new { @class = "control-label col-md-2" })
            @*JQuery*@
            @*MVC*@
            @*http://stackoverflow.com/questions/23474666/create-dropdownlist-for-an-asp-net-mvc5-relation*@
            <div class="col-md-2">
                @Html.DropDownListFor(model => model.SuperID, new SelectList(ViewBag.supers, "Identifier", "Name").OrderBy(sp => sp.Text), new { @class = "form-control" })
            </div>
            @*<div class="col-md-10">
                    <select class="form-control">
                        <option value="3">Mark S</option>
                        <option value="4">Bobby</option>
                        <option value="5">Suzy</option>
                    </select>
                </div>*@
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScheduleID, htmlAttributes: new { @class = "control-label col-md-2" })
            @*JQuery*@
            @*MVC*@
            @*http://stackoverflow.com/questions/23474666/create-dropdownlist-for-an-asp-net-mvc5-relation*@
            <div class="col-md-2">
                @Html.DropDownListFor(model => model.ScheduleID, new SelectList(ViewBag.schedules, "Identifier", "Name").OrderBy(sp => sp.Text), new { @class = "form-control" })
            </div>
            @*<div class="col-md-10">
                <select class="form-control">
                    <option value="3">Mark S</option>
                    <option value="4">Bobby</option>
                    <option value="5">Suzy</option>
                </select>
            </div>*@
        </div>
        @*<div class="form-group">
                @Html.LabelFor(model => model.Superintendent, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10"> 
                    @Html.EditorFor(model => model.Superintendent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Superintendent, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Permit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Permit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Permit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.start, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.start, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.finish, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.finish, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Finish, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "List")
</div>

Website/Views/Job/Edit.cshtml
@model Website.Models.JobModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Job</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Job edit</legend>
        <div class="editor-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.SuperID)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.SuperID, new SelectList(ViewBag.supers, "Identifier", "Name").OrderBy(sp => sp.Text))
                @Html.ValidationMessageFor(model => model.SuperID)
            </div>
        </div>
        <div class="editor-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.Permit)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Permit)
                @Html.ValidationMessageFor(model => model.Permit)
            </div>
        </div>
        <div class="editor-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.Description)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>
        <div class="editor-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="editor-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.LotIdentifier)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.LotIdentifier)
                @Html.ValidationMessageFor(model => model.LotIdentifier)
            </div>
        </div>
        <div class="editor-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.Address1)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Address1)
                @Html.ValidationMessageFor(model => model.Address1)
            </div>
        </div>
        <div class="editor-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.City)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>
        <div class="editor-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.State)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.State)
                @Html.ValidationMessageFor(model => model.State)
            </div>
        </div>
        <div class="editor-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.PostalCode)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.PostalCode)
                @Html.ValidationMessageFor(model => model.PostalCode)
            </div>
        </div>
        <div class="editor-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.start)
            </div>
            <div class="editor-field">
                @Html.ActionLink(Model.start.Value.ToString("MM/dd/yyyy"), "JobCalendar", "Super", new { jobID = Model.Identifier }, null)
            </div>
        </div>
        <div class="editor-group">
            <div class="editor-label">
                @Html.LabelFor(model => model.finish)
            </div>
            <div class="editor-field">
                @Html.ActionLink((Model.finish.HasValue ? Model.finish.Value.ToString("MM/dd/yyyy") : ""), "JobCalendar", "Super", new { jobID = Model.Identifier }, null)
            </div>
        </div>
        <div class="editor-group-clear">
            @Html.HiddenFor(model => model.BuilderID)
            @Html.HiddenFor(model => model.Identifier)
            @Html.HiddenFor(model => model.SuperID)
            @Html.HiddenFor(model => model.SuperName)
            @Html.HiddenFor(model => model.ScheduleID)
        </div>
        <div class="editor-submit">
            <p>
                <input type="submit" value="Save" />
            </p>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

Website/Views/Job/Index.cshtml
@model IEnumerable<Website.Models.JobModel>
@section Styles{
    <link href="@Url.Content("~/Content/DataTables/css/jquery.dataTables.css")" rel="stylesheet" type="text/css" />
    <style>
        table tr td {
            padding-right: 8px;
        }
    </style>
}  
@section Scripts{
    <script src="@Url.Content("~/Scripts/DataTables/jquery.dataTables.js")" type="text/javascript"></script>
    <script type="text/javascript">
        var root = "@String.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~/")).Trim('/')";
        $(document).ready(function () {
            $('table').DataTable();
            $('.deleteJob').click(function () { $('#deleteJobText').text('Are you sure you want to delete ' + $(this).attr('name') + '?'); $('#deleteLink').val($(this).attr('href')); $.blockUI({ message: $('#divConfirmDelete') }); return false; });
            $('#buttonYes').click(function () { window.location = $('#deleteLink').val(); $.unblockUI(); return true; });
            $('#buttonNo').click(function () { $.unblockUI(); return false; });
        });
    </script>
    @*<script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>*@
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")" type="text/javascript"></script>
    @*<script src="@Url.Content("~/Scripts/jquery.blockUI.js")" type="text/javascript"></script>*@
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table id="TableJobList" class="table dataTable table-striped">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Super
            </th>
            <th>
                Description
            </th>
            <th>
                Permit
            </th>
            <th>
                Start
            </th>
            <th>
                Finish
            </th>
            <th/>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SuperName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Permit)
                </td>
                <td>
                    @(@item.start.HasValue ? @item.start.Value.ToString("MM/dd/yyyy") : "")
                </td>
                <td>
                    @(@item.finish.HasValue ? @item.finish.Value.ToString("MM/dd/yyyy") : "")
                </td>
                <td>
                    @Html.ActionLink("Calendar", "JobCalendar", "Super", new { jobID = item.Identifier }, null) | 
                    @Html.ActionLink("Edit", "Edit", new { id = item.Identifier }) | 
                    @Html.ActionLink("Delete", "Delete", "Job", new { id = item.Identifier }, new { @class = "deleteJob", @name = item.Name } )
                </td>
            </tr>
        }
    </tbody>
</table>
<div id="divConfirmDelete" style="display: none; cursor: default; overflow: hidden; padding-bottom: 15px">
    <div><h2 id="deleteJobText"></h2></div>
    <div style="height: 20%; margin-top: 10px">
        <input type="hidden" id="deleteLink" />
        <input type="button" id="buttonYes" value="Yes" />
        <input type="button" id="buttonNo" value="No" />
    </div>
</div>

Website/Views/Job/List.cshtml
@model IEnumerable<Website.Models.JobListItemModel>

@{
    ViewBag.Title = "List";
}

@section styles {
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="~/Content/DataTables/css/jquery.dataTables.css">
    <style>
        .link-mine {
            color: white;
            float:right;
            margin-bottom:.5em;
            font-size:1.25em;
        }
    </style>
}

<h2>Job List</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "link-mine" })
</p>
<table class="table dataTable table-striped" id="tableJob">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LotNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Permit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Start)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Finish)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Superintendent)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LotNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Permit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Start)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Finish)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Superintendent)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Retire", "Retire", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {
    <script type="text/javascript" src="~/Scripts/DataTables/jquery.dataTables.js"> </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#tableJob').dataTable();
        });
    </script>
}